
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed2;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Entry entry10;

	private global::Gtk.Entry entry1;

	private global::Gtk.Entry entry2;

	private global::Gtk.Entry entry3;

	private global::Gtk.Entry entry4;

	private global::Gtk.Button button3;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.Label label5;

	private global::Gtk.Label label6;

	private global::Gtk.Label label7;

	private global::Gtk.Label label8;

	private global::Gtk.Label label9;

	private global::Gtk.Label label10;

	private global::Gtk.Label label11;

	private global::Gtk.Label label13;

	private global::Gtk.Label label12;

	private global::Gtk.Label label14;

	private global::Gtk.Label label15;

	private global::Gtk.Label label16;

	private global::Gtk.Label label17;

	private global::Gtk.Label label18;

	private global::Gtk.Label label19;

	private global::Gtk.Label label20;

	private global::Gtk.Label label21;

	private global::Gtk.Label label22;

	private global::Gtk.Entry entry5;

	private global::Gtk.Entry entry6;

	private global::Gtk.Entry entry7;

	private global::Gtk.Entry entry8;

	private global::Gtk.Entry entry9;

	private global::Gtk.Entry entry11;

	private global::Gtk.Entry entry12;

	private global::Gtk.Entry entry13;

	private global::Gtk.Entry entry14;

	private global::Gtk.Entry entry15;

	private global::Gtk.Entry entry16;

	private global::Gtk.Entry entry17;

	private global::Gtk.Entry entry18;

	private global::Gtk.Entry entry19;

	private global::Gtk.Entry entry20;

	private global::Gtk.Entry entry21;

	private global::Gtk.Entry entry22;

	private global::Gtk.Entry entry23;

	private global::Gtk.Entry entry24;

	private global::Gtk.Entry entry25;

	private global::Gtk.Entry entry26;

	private global::Gtk.Entry entry27;

	private global::Gtk.Entry entry28;

	private global::Gtk.Entry entry29;

	private global::Gtk.Entry entry30;

	private global::Gtk.Entry entry31;

	private global::Gtk.Entry entry32;

	private global::Gtk.Entry entry33;

	private global::Gtk.Entry entry34;

	private global::Gtk.Entry entry35;

	private global::Gtk.Entry entry36;

	private global::Gtk.Entry entry37;

	private global::Gtk.Entry entry38;

	private global::Gtk.Entry entry39;

	private global::Gtk.Entry entry40;

	private global::Gtk.Entry entry41;

	private global::Gtk.Entry entry42;

	private global::Gtk.Entry entry43;

	private global::Gtk.Entry entry44;

	private global::Gtk.Entry entry45;

	private global::Gtk.Entry entry46;

	private global::Gtk.Entry entry47;

	private global::Gtk.Entry entry48;

	private global::Gtk.Entry entry49;

	private global::Gtk.Entry entry50;

	private global::Gtk.Entry entry51;

	private global::Gtk.Entry entry52;

	private global::Gtk.Entry entry53;

	private global::Gtk.Entry entry54;

	private global::Gtk.Entry entry55;

	private global::Gtk.Entry entry56;

	private global::Gtk.Entry entry57;

	private global::Gtk.Entry entry58;

	private global::Gtk.Entry entry59;

	private global::Gtk.Entry entry60;

	private global::Gtk.Entry entry61;

	private global::Gtk.Entry entry62;

	private global::Gtk.CheckButton checkbutton1;

	private global::Gtk.CheckButton checkbutton2;

	private global::Gtk.CheckButton checkbutton3;

	private global::Gtk.CheckButton checkbutton4;

	private global::Gtk.CheckButton checkbutton5;

	private global::Gtk.Entry entry63;

	private global::Gtk.Label label23;

	private global::Gtk.Button button4;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(12));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Start spil");
		this.fixed2.Add(this.button1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.button1]));
		w1.X = 45;
		w1.Y = 10;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Slut spil");
		this.fixed2.Add(this.button2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.button2]));
		w2.X = 145;
		w2.Y = 10;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry10 = new global::Gtk.Entry();
		this.entry10.WidthRequest = 100;
		this.entry10.HeightRequest = 0;
		this.entry10.CanFocus = true;
		this.entry10.Name = "entry10";
		this.entry10.IsEditable = true;
		this.entry10.InvisibleChar = '●';
		this.fixed2.Add(this.entry10);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry10]));
		w3.X = 40;
		w3.Y = 50;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.WidthRequest = 100;
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.fixed2.Add(this.entry1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry1]));
		w4.X = 140;
		w4.Y = 50;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.WidthRequest = 100;
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.fixed2.Add(this.entry2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry2]));
		w5.X = 240;
		w5.Y = 50;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.WidthRequest = 100;
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.fixed2.Add(this.entry3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry3]));
		w6.X = 340;
		w6.Y = 50;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry4 = new global::Gtk.Entry();
		this.entry4.WidthRequest = 100;
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '●';
		this.fixed2.Add(this.entry4);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry4]));
		w7.X = 440;
		w7.Y = 50;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Slå terninger");
		this.fixed2.Add(this.button3);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.button3]));
		w8.X = 550;
		w8.Y = 47;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Navn:");
		this.fixed2.Add(this.label1);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label1]));
		w9.X = 45;
		w9.Y = 130;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("1\'ere");
		this.fixed2.Add(this.label2);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label2]));
		w10.X = 45;
		w10.Y = 160;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("2\'ere");
		this.fixed2.Add(this.label3);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label3]));
		w11.X = 45;
		w11.Y = 190;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("3\'ere");
		this.fixed2.Add(this.label4);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label4]));
		w12.X = 45;
		w12.Y = 220;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("4\'ere");
		this.fixed2.Add(this.label5);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label5]));
		w13.X = 45;
		w13.Y = 250;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("5\'ere");
		this.fixed2.Add(this.label6);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label6]));
		w14.X = 45;
		w14.Y = 280;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("6\'ere");
		this.fixed2.Add(this.label7);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label7]));
		w15.X = 45;
		w15.Y = 310;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.Xalign = 0F;
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("SUM");
		this.fixed2.Add(this.label8);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label8]));
		w16.X = 45;
		w16.Y = 340;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Bonus");
		this.fixed2.Add(this.label9);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label9]));
		w17.X = 45;
		w17.Y = 370;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("1 par");
		this.fixed2.Add(this.label10);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label10]));
		w18.X = 45;
		w18.Y = 400;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("2 par");
		this.fixed2.Add(this.label11);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label11]));
		w19.X = 45;
		w19.Y = 430;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("4 ens");
		this.fixed2.Add(this.label13);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label13]));
		w20.X = 45;
		w20.Y = 490;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("3 ens");
		this.fixed2.Add(this.label12);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label12]));
		w21.X = 45;
		w21.Y = 460;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Lille");
		this.fixed2.Add(this.label14);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label14]));
		w22.X = 45;
		w22.Y = 520;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.label15.Xalign = 0F;
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Stor");
		this.fixed2.Add(this.label15);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label15]));
		w23.X = 45;
		w23.Y = 550;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label16 = new global::Gtk.Label();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Hus");
		this.fixed2.Add(this.label16);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label16]));
		w24.X = 45;
		w24.Y = 580;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Chancen");
		this.fixed2.Add(this.label17);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label17]));
		w25.X = 45;
		w25.Y = 610;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label18 = new global::Gtk.Label();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Yatzy");
		this.fixed2.Add(this.label18);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label18]));
		w26.X = 45;
		w26.Y = 640;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label19 = new global::Gtk.Label();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("SUM");
		this.fixed2.Add(this.label19);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label19]));
		w27.X = 45;
		w27.Y = 670;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label20 = new global::Gtk.Label();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Spiller 1");
		this.fixed2.Add(this.label20);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label20]));
		w28.X = 145;
		w28.Y = 110;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label21 = new global::Gtk.Label();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Spiller 2");
		this.fixed2.Add(this.label21);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label21]));
		w29.X = 245;
		w29.Y = 110;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label22 = new global::Gtk.Label();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Spiller 3");
		this.fixed2.Add(this.label22);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label22]));
		w30.X = 345;
		w30.Y = 110;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry5 = new global::Gtk.Entry();
		this.entry5.WidthRequest = 100;
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '●';
		this.fixed2.Add(this.entry5);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry5]));
		w31.X = 140;
		w31.Y = 125;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry6 = new global::Gtk.Entry();
		this.entry6.WidthRequest = 100;
		this.entry6.CanFocus = true;
		this.entry6.Name = "entry6";
		this.entry6.IsEditable = true;
		this.entry6.InvisibleChar = '●';
		this.fixed2.Add(this.entry6);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry6]));
		w32.X = 140;
		w32.Y = 155;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry7 = new global::Gtk.Entry();
		this.entry7.WidthRequest = 100;
		this.entry7.CanFocus = true;
		this.entry7.Name = "entry7";
		this.entry7.IsEditable = true;
		this.entry7.InvisibleChar = '●';
		this.fixed2.Add(this.entry7);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry7]));
		w33.X = 140;
		w33.Y = 185;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry8 = new global::Gtk.Entry();
		this.entry8.WidthRequest = 100;
		this.entry8.CanFocus = true;
		this.entry8.Name = "entry8";
		this.entry8.IsEditable = true;
		this.entry8.InvisibleChar = '●';
		this.fixed2.Add(this.entry8);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry8]));
		w34.X = 140;
		w34.Y = 215;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry9 = new global::Gtk.Entry();
		this.entry9.WidthRequest = 100;
		this.entry9.CanFocus = true;
		this.entry9.Name = "entry9";
		this.entry9.IsEditable = true;
		this.entry9.InvisibleChar = '●';
		this.fixed2.Add(this.entry9);
		global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry9]));
		w35.X = 140;
		w35.Y = 245;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry11 = new global::Gtk.Entry();
		this.entry11.WidthRequest = 100;
		this.entry11.CanFocus = true;
		this.entry11.Name = "entry11";
		this.entry11.IsEditable = true;
		this.entry11.InvisibleChar = '●';
		this.fixed2.Add(this.entry11);
		global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry11]));
		w36.X = 140;
		w36.Y = 275;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry12 = new global::Gtk.Entry();
		this.entry12.WidthRequest = 100;
		this.entry12.CanFocus = true;
		this.entry12.Name = "entry12";
		this.entry12.IsEditable = true;
		this.entry12.InvisibleChar = '●';
		this.fixed2.Add(this.entry12);
		global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry12]));
		w37.X = 140;
		w37.Y = 305;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry13 = new global::Gtk.Entry();
		this.entry13.WidthRequest = 100;
		this.entry13.CanFocus = true;
		this.entry13.Name = "entry13";
		this.entry13.IsEditable = true;
		this.entry13.InvisibleChar = '●';
		this.fixed2.Add(this.entry13);
		global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry13]));
		w38.X = 140;
		w38.Y = 335;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry14 = new global::Gtk.Entry();
		this.entry14.WidthRequest = 100;
		this.entry14.CanFocus = true;
		this.entry14.Name = "entry14";
		this.entry14.IsEditable = true;
		this.entry14.InvisibleChar = '●';
		this.fixed2.Add(this.entry14);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry14]));
		w39.X = 140;
		w39.Y = 365;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry15 = new global::Gtk.Entry();
		this.entry15.WidthRequest = 100;
		this.entry15.CanFocus = true;
		this.entry15.Name = "entry15";
		this.entry15.IsEditable = true;
		this.entry15.InvisibleChar = '●';
		this.fixed2.Add(this.entry15);
		global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry15]));
		w40.X = 140;
		w40.Y = 395;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry16 = new global::Gtk.Entry();
		this.entry16.WidthRequest = 100;
		this.entry16.CanFocus = true;
		this.entry16.Name = "entry16";
		this.entry16.IsEditable = true;
		this.entry16.InvisibleChar = '●';
		this.fixed2.Add(this.entry16);
		global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry16]));
		w41.X = 140;
		w41.Y = 425;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry17 = new global::Gtk.Entry();
		this.entry17.WidthRequest = 100;
		this.entry17.CanFocus = true;
		this.entry17.Name = "entry17";
		this.entry17.IsEditable = true;
		this.entry17.InvisibleChar = '●';
		this.fixed2.Add(this.entry17);
		global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry17]));
		w42.X = 140;
		w42.Y = 455;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry18 = new global::Gtk.Entry();
		this.entry18.WidthRequest = 100;
		this.entry18.CanFocus = true;
		this.entry18.Name = "entry18";
		this.entry18.IsEditable = true;
		this.entry18.InvisibleChar = '●';
		this.fixed2.Add(this.entry18);
		global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry18]));
		w43.X = 140;
		w43.Y = 485;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry19 = new global::Gtk.Entry();
		this.entry19.WidthRequest = 100;
		this.entry19.CanFocus = true;
		this.entry19.Name = "entry19";
		this.entry19.IsEditable = true;
		this.entry19.InvisibleChar = '●';
		this.fixed2.Add(this.entry19);
		global::Gtk.Fixed.FixedChild w44 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry19]));
		w44.X = 140;
		w44.Y = 515;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry20 = new global::Gtk.Entry();
		this.entry20.WidthRequest = 100;
		this.entry20.CanFocus = true;
		this.entry20.Name = "entry20";
		this.entry20.IsEditable = true;
		this.entry20.InvisibleChar = '●';
		this.fixed2.Add(this.entry20);
		global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry20]));
		w45.X = 140;
		w45.Y = 545;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry21 = new global::Gtk.Entry();
		this.entry21.WidthRequest = 100;
		this.entry21.CanFocus = true;
		this.entry21.Name = "entry21";
		this.entry21.IsEditable = true;
		this.entry21.InvisibleChar = '●';
		this.fixed2.Add(this.entry21);
		global::Gtk.Fixed.FixedChild w46 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry21]));
		w46.X = 140;
		w46.Y = 575;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry22 = new global::Gtk.Entry();
		this.entry22.WidthRequest = 100;
		this.entry22.CanFocus = true;
		this.entry22.Name = "entry22";
		this.entry22.IsEditable = true;
		this.entry22.InvisibleChar = '●';
		this.fixed2.Add(this.entry22);
		global::Gtk.Fixed.FixedChild w47 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry22]));
		w47.X = 140;
		w47.Y = 605;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry23 = new global::Gtk.Entry();
		this.entry23.WidthRequest = 100;
		this.entry23.CanFocus = true;
		this.entry23.Name = "entry23";
		this.entry23.IsEditable = true;
		this.entry23.InvisibleChar = '●';
		this.fixed2.Add(this.entry23);
		global::Gtk.Fixed.FixedChild w48 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry23]));
		w48.X = 140;
		w48.Y = 635;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry24 = new global::Gtk.Entry();
		this.entry24.WidthRequest = 100;
		this.entry24.CanFocus = true;
		this.entry24.Name = "entry24";
		this.entry24.IsEditable = true;
		this.entry24.InvisibleChar = '●';
		this.fixed2.Add(this.entry24);
		global::Gtk.Fixed.FixedChild w49 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry24]));
		w49.X = 140;
		w49.Y = 665;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry25 = new global::Gtk.Entry();
		this.entry25.WidthRequest = 100;
		this.entry25.CanFocus = true;
		this.entry25.Name = "entry25";
		this.entry25.IsEditable = true;
		this.entry25.InvisibleChar = '●';
		this.fixed2.Add(this.entry25);
		global::Gtk.Fixed.FixedChild w50 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry25]));
		w50.X = 240;
		w50.Y = 125;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry26 = new global::Gtk.Entry();
		this.entry26.WidthRequest = 100;
		this.entry26.CanFocus = true;
		this.entry26.Name = "entry26";
		this.entry26.IsEditable = true;
		this.entry26.InvisibleChar = '●';
		this.fixed2.Add(this.entry26);
		global::Gtk.Fixed.FixedChild w51 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry26]));
		w51.X = 240;
		w51.Y = 155;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry27 = new global::Gtk.Entry();
		this.entry27.WidthRequest = 100;
		this.entry27.CanFocus = true;
		this.entry27.Name = "entry27";
		this.entry27.IsEditable = true;
		this.entry27.InvisibleChar = '●';
		this.fixed2.Add(this.entry27);
		global::Gtk.Fixed.FixedChild w52 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry27]));
		w52.X = 240;
		w52.Y = 185;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry28 = new global::Gtk.Entry();
		this.entry28.WidthRequest = 100;
		this.entry28.CanFocus = true;
		this.entry28.Name = "entry28";
		this.entry28.IsEditable = true;
		this.entry28.InvisibleChar = '●';
		this.fixed2.Add(this.entry28);
		global::Gtk.Fixed.FixedChild w53 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry28]));
		w53.X = 240;
		w53.Y = 215;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry29 = new global::Gtk.Entry();
		this.entry29.WidthRequest = 100;
		this.entry29.CanFocus = true;
		this.entry29.Name = "entry29";
		this.entry29.IsEditable = true;
		this.entry29.InvisibleChar = '●';
		this.fixed2.Add(this.entry29);
		global::Gtk.Fixed.FixedChild w54 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry29]));
		w54.X = 240;
		w54.Y = 245;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry30 = new global::Gtk.Entry();
		this.entry30.WidthRequest = 100;
		this.entry30.CanFocus = true;
		this.entry30.Name = "entry30";
		this.entry30.IsEditable = true;
		this.entry30.InvisibleChar = '●';
		this.fixed2.Add(this.entry30);
		global::Gtk.Fixed.FixedChild w55 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry30]));
		w55.X = 240;
		w55.Y = 275;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry31 = new global::Gtk.Entry();
		this.entry31.WidthRequest = 100;
		this.entry31.CanFocus = true;
		this.entry31.Name = "entry31";
		this.entry31.IsEditable = true;
		this.entry31.InvisibleChar = '●';
		this.fixed2.Add(this.entry31);
		global::Gtk.Fixed.FixedChild w56 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry31]));
		w56.X = 240;
		w56.Y = 305;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry32 = new global::Gtk.Entry();
		this.entry32.WidthRequest = 100;
		this.entry32.CanFocus = true;
		this.entry32.Name = "entry32";
		this.entry32.IsEditable = true;
		this.entry32.InvisibleChar = '●';
		this.fixed2.Add(this.entry32);
		global::Gtk.Fixed.FixedChild w57 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry32]));
		w57.X = 240;
		w57.Y = 335;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry33 = new global::Gtk.Entry();
		this.entry33.WidthRequest = 100;
		this.entry33.CanFocus = true;
		this.entry33.Name = "entry33";
		this.entry33.IsEditable = true;
		this.entry33.InvisibleChar = '●';
		this.fixed2.Add(this.entry33);
		global::Gtk.Fixed.FixedChild w58 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry33]));
		w58.X = 240;
		w58.Y = 365;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry34 = new global::Gtk.Entry();
		this.entry34.WidthRequest = 100;
		this.entry34.CanFocus = true;
		this.entry34.Name = "entry34";
		this.entry34.IsEditable = true;
		this.entry34.InvisibleChar = '●';
		this.fixed2.Add(this.entry34);
		global::Gtk.Fixed.FixedChild w59 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry34]));
		w59.X = 240;
		w59.Y = 395;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry35 = new global::Gtk.Entry();
		this.entry35.WidthRequest = 100;
		this.entry35.CanFocus = true;
		this.entry35.Name = "entry35";
		this.entry35.IsEditable = true;
		this.entry35.InvisibleChar = '●';
		this.fixed2.Add(this.entry35);
		global::Gtk.Fixed.FixedChild w60 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry35]));
		w60.X = 240;
		w60.Y = 425;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry36 = new global::Gtk.Entry();
		this.entry36.WidthRequest = 100;
		this.entry36.CanFocus = true;
		this.entry36.Name = "entry36";
		this.entry36.IsEditable = true;
		this.entry36.InvisibleChar = '●';
		this.fixed2.Add(this.entry36);
		global::Gtk.Fixed.FixedChild w61 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry36]));
		w61.X = 240;
		w61.Y = 455;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry37 = new global::Gtk.Entry();
		this.entry37.WidthRequest = 100;
		this.entry37.CanFocus = true;
		this.entry37.Name = "entry37";
		this.entry37.IsEditable = true;
		this.entry37.InvisibleChar = '●';
		this.fixed2.Add(this.entry37);
		global::Gtk.Fixed.FixedChild w62 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry37]));
		w62.X = 240;
		w62.Y = 485;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry38 = new global::Gtk.Entry();
		this.entry38.WidthRequest = 100;
		this.entry38.CanFocus = true;
		this.entry38.Name = "entry38";
		this.entry38.IsEditable = true;
		this.entry38.InvisibleChar = '●';
		this.fixed2.Add(this.entry38);
		global::Gtk.Fixed.FixedChild w63 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry38]));
		w63.X = 240;
		w63.Y = 515;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry39 = new global::Gtk.Entry();
		this.entry39.WidthRequest = 100;
		this.entry39.CanFocus = true;
		this.entry39.Name = "entry39";
		this.entry39.IsEditable = true;
		this.entry39.InvisibleChar = '●';
		this.fixed2.Add(this.entry39);
		global::Gtk.Fixed.FixedChild w64 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry39]));
		w64.X = 240;
		w64.Y = 545;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry40 = new global::Gtk.Entry();
		this.entry40.WidthRequest = 100;
		this.entry40.CanFocus = true;
		this.entry40.Name = "entry40";
		this.entry40.IsEditable = true;
		this.entry40.InvisibleChar = '●';
		this.fixed2.Add(this.entry40);
		global::Gtk.Fixed.FixedChild w65 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry40]));
		w65.X = 240;
		w65.Y = 575;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry41 = new global::Gtk.Entry();
		this.entry41.WidthRequest = 100;
		this.entry41.CanFocus = true;
		this.entry41.Name = "entry41";
		this.entry41.IsEditable = true;
		this.entry41.InvisibleChar = '●';
		this.fixed2.Add(this.entry41);
		global::Gtk.Fixed.FixedChild w66 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry41]));
		w66.X = 240;
		w66.Y = 605;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry42 = new global::Gtk.Entry();
		this.entry42.WidthRequest = 100;
		this.entry42.CanFocus = true;
		this.entry42.Name = "entry42";
		this.entry42.IsEditable = true;
		this.entry42.InvisibleChar = '●';
		this.fixed2.Add(this.entry42);
		global::Gtk.Fixed.FixedChild w67 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry42]));
		w67.X = 240;
		w67.Y = 635;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry43 = new global::Gtk.Entry();
		this.entry43.WidthRequest = 100;
		this.entry43.CanFocus = true;
		this.entry43.Name = "entry43";
		this.entry43.IsEditable = true;
		this.entry43.InvisibleChar = '●';
		this.fixed2.Add(this.entry43);
		global::Gtk.Fixed.FixedChild w68 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry43]));
		w68.X = 240;
		w68.Y = 665;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry44 = new global::Gtk.Entry();
		this.entry44.WidthRequest = 100;
		this.entry44.CanFocus = true;
		this.entry44.Name = "entry44";
		this.entry44.IsEditable = true;
		this.entry44.InvisibleChar = '●';
		this.fixed2.Add(this.entry44);
		global::Gtk.Fixed.FixedChild w69 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry44]));
		w69.X = 340;
		w69.Y = 125;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry45 = new global::Gtk.Entry();
		this.entry45.WidthRequest = 100;
		this.entry45.CanFocus = true;
		this.entry45.Name = "entry45";
		this.entry45.IsEditable = true;
		this.entry45.InvisibleChar = '●';
		this.fixed2.Add(this.entry45);
		global::Gtk.Fixed.FixedChild w70 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry45]));
		w70.X = 340;
		w70.Y = 155;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry46 = new global::Gtk.Entry();
		this.entry46.WidthRequest = 100;
		this.entry46.CanFocus = true;
		this.entry46.Name = "entry46";
		this.entry46.IsEditable = true;
		this.entry46.InvisibleChar = '●';
		this.fixed2.Add(this.entry46);
		global::Gtk.Fixed.FixedChild w71 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry46]));
		w71.X = 340;
		w71.Y = 185;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry47 = new global::Gtk.Entry();
		this.entry47.WidthRequest = 100;
		this.entry47.CanFocus = true;
		this.entry47.Name = "entry47";
		this.entry47.IsEditable = true;
		this.entry47.InvisibleChar = '●';
		this.fixed2.Add(this.entry47);
		global::Gtk.Fixed.FixedChild w72 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry47]));
		w72.X = 340;
		w72.Y = 215;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry48 = new global::Gtk.Entry();
		this.entry48.WidthRequest = 100;
		this.entry48.CanFocus = true;
		this.entry48.Name = "entry48";
		this.entry48.IsEditable = true;
		this.entry48.InvisibleChar = '●';
		this.fixed2.Add(this.entry48);
		global::Gtk.Fixed.FixedChild w73 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry48]));
		w73.X = 340;
		w73.Y = 245;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry49 = new global::Gtk.Entry();
		this.entry49.WidthRequest = 100;
		this.entry49.CanFocus = true;
		this.entry49.Name = "entry49";
		this.entry49.IsEditable = true;
		this.entry49.InvisibleChar = '●';
		this.fixed2.Add(this.entry49);
		global::Gtk.Fixed.FixedChild w74 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry49]));
		w74.X = 340;
		w74.Y = 275;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry50 = new global::Gtk.Entry();
		this.entry50.WidthRequest = 100;
		this.entry50.CanFocus = true;
		this.entry50.Name = "entry50";
		this.entry50.IsEditable = true;
		this.entry50.InvisibleChar = '●';
		this.fixed2.Add(this.entry50);
		global::Gtk.Fixed.FixedChild w75 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry50]));
		w75.X = 340;
		w75.Y = 305;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry51 = new global::Gtk.Entry();
		this.entry51.WidthRequest = 100;
		this.entry51.CanFocus = true;
		this.entry51.Name = "entry51";
		this.entry51.IsEditable = true;
		this.entry51.InvisibleChar = '●';
		this.fixed2.Add(this.entry51);
		global::Gtk.Fixed.FixedChild w76 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry51]));
		w76.X = 340;
		w76.Y = 335;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry52 = new global::Gtk.Entry();
		this.entry52.WidthRequest = 100;
		this.entry52.CanFocus = true;
		this.entry52.Name = "entry52";
		this.entry52.IsEditable = true;
		this.entry52.InvisibleChar = '●';
		this.fixed2.Add(this.entry52);
		global::Gtk.Fixed.FixedChild w77 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry52]));
		w77.X = 340;
		w77.Y = 365;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry53 = new global::Gtk.Entry();
		this.entry53.WidthRequest = 100;
		this.entry53.CanFocus = true;
		this.entry53.Name = "entry53";
		this.entry53.IsEditable = true;
		this.entry53.InvisibleChar = '●';
		this.fixed2.Add(this.entry53);
		global::Gtk.Fixed.FixedChild w78 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry53]));
		w78.X = 340;
		w78.Y = 395;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry54 = new global::Gtk.Entry();
		this.entry54.WidthRequest = 100;
		this.entry54.CanFocus = true;
		this.entry54.Name = "entry54";
		this.entry54.IsEditable = true;
		this.entry54.InvisibleChar = '●';
		this.fixed2.Add(this.entry54);
		global::Gtk.Fixed.FixedChild w79 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry54]));
		w79.X = 340;
		w79.Y = 425;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry55 = new global::Gtk.Entry();
		this.entry55.WidthRequest = 100;
		this.entry55.CanFocus = true;
		this.entry55.Name = "entry55";
		this.entry55.IsEditable = true;
		this.entry55.InvisibleChar = '●';
		this.fixed2.Add(this.entry55);
		global::Gtk.Fixed.FixedChild w80 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry55]));
		w80.X = 340;
		w80.Y = 455;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry56 = new global::Gtk.Entry();
		this.entry56.WidthRequest = 100;
		this.entry56.CanFocus = true;
		this.entry56.Name = "entry56";
		this.entry56.IsEditable = true;
		this.entry56.InvisibleChar = '●';
		this.fixed2.Add(this.entry56);
		global::Gtk.Fixed.FixedChild w81 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry56]));
		w81.X = 340;
		w81.Y = 485;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry57 = new global::Gtk.Entry();
		this.entry57.WidthRequest = 100;
		this.entry57.CanFocus = true;
		this.entry57.Name = "entry57";
		this.entry57.IsEditable = true;
		this.entry57.InvisibleChar = '●';
		this.fixed2.Add(this.entry57);
		global::Gtk.Fixed.FixedChild w82 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry57]));
		w82.X = 340;
		w82.Y = 515;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry58 = new global::Gtk.Entry();
		this.entry58.WidthRequest = 100;
		this.entry58.CanFocus = true;
		this.entry58.Name = "entry58";
		this.entry58.IsEditable = true;
		this.entry58.InvisibleChar = '●';
		this.fixed2.Add(this.entry58);
		global::Gtk.Fixed.FixedChild w83 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry58]));
		w83.X = 340;
		w83.Y = 545;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry59 = new global::Gtk.Entry();
		this.entry59.WidthRequest = 100;
		this.entry59.CanFocus = true;
		this.entry59.Name = "entry59";
		this.entry59.IsEditable = true;
		this.entry59.InvisibleChar = '●';
		this.fixed2.Add(this.entry59);
		global::Gtk.Fixed.FixedChild w84 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry59]));
		w84.X = 340;
		w84.Y = 575;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry60 = new global::Gtk.Entry();
		this.entry60.WidthRequest = 100;
		this.entry60.CanFocus = true;
		this.entry60.Name = "entry60";
		this.entry60.IsEditable = true;
		this.entry60.InvisibleChar = '●';
		this.fixed2.Add(this.entry60);
		global::Gtk.Fixed.FixedChild w85 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry60]));
		w85.X = 340;
		w85.Y = 605;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry61 = new global::Gtk.Entry();
		this.entry61.WidthRequest = 100;
		this.entry61.CanFocus = true;
		this.entry61.Name = "entry61";
		this.entry61.IsEditable = true;
		this.entry61.InvisibleChar = '●';
		this.fixed2.Add(this.entry61);
		global::Gtk.Fixed.FixedChild w86 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry61]));
		w86.X = 340;
		w86.Y = 635;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry62 = new global::Gtk.Entry();
		this.entry62.WidthRequest = 100;
		this.entry62.CanFocus = true;
		this.entry62.Name = "entry62";
		this.entry62.IsEditable = true;
		this.entry62.InvisibleChar = '●';
		this.fixed2.Add(this.entry62);
		global::Gtk.Fixed.FixedChild w87 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry62]));
		w87.X = 340;
		w87.Y = 665;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.checkbutton1 = new global::Gtk.CheckButton();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.fixed2.Add(this.checkbutton1);
		global::Gtk.Fixed.FixedChild w88 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.checkbutton1]));
		w88.X = 40;
		w88.Y = 70;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.checkbutton2 = new global::Gtk.CheckButton();
		this.checkbutton2.CanFocus = true;
		this.checkbutton2.Name = "checkbutton2";
		this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.checkbutton2.DrawIndicator = true;
		this.checkbutton2.UseUnderline = true;
		this.fixed2.Add(this.checkbutton2);
		global::Gtk.Fixed.FixedChild w89 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.checkbutton2]));
		w89.X = 140;
		w89.Y = 70;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.checkbutton3 = new global::Gtk.CheckButton();
		this.checkbutton3.CanFocus = true;
		this.checkbutton3.Name = "checkbutton3";
		this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.checkbutton3.DrawIndicator = true;
		this.checkbutton3.UseUnderline = true;
		this.fixed2.Add(this.checkbutton3);
		global::Gtk.Fixed.FixedChild w90 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.checkbutton3]));
		w90.X = 240;
		w90.Y = 70;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.checkbutton4 = new global::Gtk.CheckButton();
		this.checkbutton4.CanFocus = true;
		this.checkbutton4.Name = "checkbutton4";
		this.checkbutton4.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.checkbutton4.DrawIndicator = true;
		this.checkbutton4.UseUnderline = true;
		this.fixed2.Add(this.checkbutton4);
		global::Gtk.Fixed.FixedChild w91 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.checkbutton4]));
		w91.X = 340;
		w91.Y = 70;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.checkbutton5 = new global::Gtk.CheckButton();
		this.checkbutton5.CanFocus = true;
		this.checkbutton5.Name = "checkbutton5";
		this.checkbutton5.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.checkbutton5.DrawIndicator = true;
		this.checkbutton5.UseUnderline = true;
		this.fixed2.Add(this.checkbutton5);
		global::Gtk.Fixed.FixedChild w92 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.checkbutton5]));
		w92.X = 440;
		w92.Y = 70;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry63 = new global::Gtk.Entry();
		this.entry63.WidthRequest = 145;
		this.entry63.HeightRequest = 202;
		this.entry63.CanFocus = true;
		this.entry63.Name = "entry63";
		this.entry63.IsEditable = true;
		this.entry63.InvisibleChar = '●';
		this.fixed2.Add(this.entry63);
		global::Gtk.Fixed.FixedChild w93 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry63]));
		w93.X = 490;
		w93.Y = 125;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label23 = new global::Gtk.Label();
		this.label23.Name = "label23";
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Muligheder:");
		this.fixed2.Add(this.label23);
		global::Gtk.Fixed.FixedChild w94 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label23]));
		w94.X = 495;
		w94.Y = 110;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Vælg");
		this.fixed2.Add(this.button4);
		global::Gtk.Fixed.FixedChild w95 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.button4]));
		w95.X = 592;
		w95.Y = 98;
		this.Add(this.fixed2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 706;
		this.DefaultHeight = 739;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
