
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed2;

	private global::Gtk.Button StartSpilKnap;

	private global::Gtk.Button SlutSpilKnap;

	private global::Gtk.Entry Terning1;

	private global::Gtk.Entry Terning2;

	private global::Gtk.Entry Terning3;

	private global::Gtk.Entry Terning4;

	private global::Gtk.Entry Terning5;

	private global::Gtk.Button KastTerningKnap;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.Label label5;

	private global::Gtk.Label label6;

	private global::Gtk.Label label7;

	private global::Gtk.Label label8;

	private global::Gtk.Label label9;

	private global::Gtk.Label label10;

	private global::Gtk.Label label11;

	private global::Gtk.Label label13;

	private global::Gtk.Label label12;

	private global::Gtk.Label label14;

	private global::Gtk.Label label15;

	private global::Gtk.Label label16;

	private global::Gtk.Label label17;

	private global::Gtk.Label label18;

	private global::Gtk.Label label19;

	private global::Gtk.Label label20;

	private global::Gtk.Label label21;

	private global::Gtk.Label label22;

	private global::Gtk.Entry NavnSpiller1;

	private global::Gtk.Entry enereSpiller1;

	private global::Gtk.Entry toereSpiller1;

	private global::Gtk.Entry treereSpiller1;

	private global::Gtk.Entry fireereSpiller1;

	private global::Gtk.Entry femereSpiller1;

	private global::Gtk.Entry seksereSpiller1;

	private global::Gtk.Entry DelSumSpiller1;

	private global::Gtk.Entry BonusSpiller1;

	private global::Gtk.Entry etparSpiller1;

	private global::Gtk.Entry toparSpiller1;

	private global::Gtk.Entry treensSpiller1;

	private global::Gtk.Entry fireensSpiller1;

	private global::Gtk.Entry LilleSpiller1;

	private global::Gtk.Entry StorSpiller1;

	private global::Gtk.Entry HusSpiller1;

	private global::Gtk.Entry ChancenSpiller1;

	private global::Gtk.Entry YatzySpiller1;

	private global::Gtk.Entry SumSpiller1;

	private global::Gtk.Entry NavnSpiller2;

	private global::Gtk.Entry enereSpiller2;

	private global::Gtk.Entry toereSpiller2;

	private global::Gtk.Entry treereSpiller2;

	private global::Gtk.Entry fireereSpiller2;

	private global::Gtk.Entry femereSpiller2;

	private global::Gtk.Entry seksereSpiller2;

	private global::Gtk.Entry DelSumSpiller2;

	private global::Gtk.Entry BonusSpiller2;

	private global::Gtk.Entry etparSpiller2;

	private global::Gtk.Entry toparSpiller2;

	private global::Gtk.Entry treensSpiller2;

	private global::Gtk.Entry fireensSpiller2;

	private global::Gtk.Entry LilleSpiller2;

	private global::Gtk.Entry StorSpiller2;

	private global::Gtk.Entry HusSpiller2;

	private global::Gtk.Entry ChancenSpiller2;

	private global::Gtk.Entry YatzySpiller2;

	private global::Gtk.Entry SumSpiller2;

	private global::Gtk.Entry NavnSpiller3;

	private global::Gtk.Entry enereSpiller3;

	private global::Gtk.Entry toereSpiller3;

	private global::Gtk.Entry treereSpiller3;

	private global::Gtk.Entry fireereSpiller3;

	private global::Gtk.Entry femereSpiller3;

	private global::Gtk.Entry seksereSpiller3;

	private global::Gtk.Entry DelSumSpiller3;

	private global::Gtk.Entry BonusSpiller3;

	private global::Gtk.Entry etparSpiller3;

	private global::Gtk.Entry toparSpiller3;

	private global::Gtk.Entry treensSpiller3;

	private global::Gtk.Entry fireensSpiller3;

	private global::Gtk.Entry LilleSpiller3;

	private global::Gtk.Entry StorSpiller3;

	private global::Gtk.Entry HusSpiller3;

	private global::Gtk.Entry ChancenSpiller3;

	private global::Gtk.Entry YatzySpiller3;

	private global::Gtk.Entry SumSpiller3;

	private global::Gtk.CheckButton HoldTerning1;

	private global::Gtk.CheckButton HoldTerning2;

	private global::Gtk.CheckButton HoldTerning3;

	private global::Gtk.CheckButton HoldTerning4;

	private global::Gtk.CheckButton HoldTerning5;

	private global::Gtk.Label label23;

	private global::Gtk.Button button4;

	private global::Gtk.ComboBoxEntry mulighederCombo;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(12));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.StartSpilKnap = new global::Gtk.Button();
		this.StartSpilKnap.CanFocus = true;
		this.StartSpilKnap.Name = "StartSpilKnap";
		this.StartSpilKnap.UseUnderline = true;
		this.StartSpilKnap.Label = global::Mono.Unix.Catalog.GetString("Start spil");
		this.fixed2.Add(this.StartSpilKnap);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.StartSpilKnap]));
		w1.X = 45;
		w1.Y = 10;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.SlutSpilKnap = new global::Gtk.Button();
		this.SlutSpilKnap.CanFocus = true;
		this.SlutSpilKnap.Name = "SlutSpilKnap";
		this.SlutSpilKnap.UseUnderline = true;
		this.SlutSpilKnap.Label = global::Mono.Unix.Catalog.GetString("Slut spil");
		this.fixed2.Add(this.SlutSpilKnap);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.SlutSpilKnap]));
		w2.X = 115;
		w2.Y = 10;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.Terning1 = new global::Gtk.Entry();
		this.Terning1.WidthRequest = 100;
		this.Terning1.HeightRequest = 0;
		this.Terning1.CanFocus = true;
		this.Terning1.Name = "Terning1";
		this.Terning1.IsEditable = false;
		this.Terning1.InvisibleChar = '●';
		this.fixed2.Add(this.Terning1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.Terning1]));
		w3.X = 40;
		w3.Y = 50;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.Terning2 = new global::Gtk.Entry();
		this.Terning2.WidthRequest = 100;
		this.Terning2.CanFocus = true;
		this.Terning2.Name = "Terning2";
		this.Terning2.IsEditable = false;
		this.Terning2.InvisibleChar = '●';
		this.fixed2.Add(this.Terning2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.Terning2]));
		w4.X = 140;
		w4.Y = 50;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.Terning3 = new global::Gtk.Entry();
		this.Terning3.WidthRequest = 100;
		this.Terning3.CanFocus = true;
		this.Terning3.Name = "Terning3";
		this.Terning3.IsEditable = false;
		this.Terning3.InvisibleChar = '●';
		this.fixed2.Add(this.Terning3);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.Terning3]));
		w5.X = 240;
		w5.Y = 50;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.Terning4 = new global::Gtk.Entry();
		this.Terning4.WidthRequest = 100;
		this.Terning4.CanFocus = true;
		this.Terning4.Name = "Terning4";
		this.Terning4.IsEditable = false;
		this.Terning4.InvisibleChar = '●';
		this.fixed2.Add(this.Terning4);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.Terning4]));
		w6.X = 340;
		w6.Y = 50;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.Terning5 = new global::Gtk.Entry();
		this.Terning5.WidthRequest = 100;
		this.Terning5.CanFocus = true;
		this.Terning5.Name = "Terning5";
		this.Terning5.IsEditable = false;
		this.Terning5.InvisibleChar = '●';
		this.fixed2.Add(this.Terning5);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.Terning5]));
		w7.X = 440;
		w7.Y = 50;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.KastTerningKnap = new global::Gtk.Button();
		this.KastTerningKnap.CanFocus = true;
		this.KastTerningKnap.Name = "KastTerningKnap";
		this.KastTerningKnap.UseUnderline = true;
		this.KastTerningKnap.Label = global::Mono.Unix.Catalog.GetString("Kast terninger");
		this.fixed2.Add(this.KastTerningKnap);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.KastTerningKnap]));
		w8.X = 550;
		w8.Y = 47;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Navn:");
		this.fixed2.Add(this.label1);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label1]));
		w9.X = 45;
		w9.Y = 130;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("1\'ere");
		this.fixed2.Add(this.label2);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label2]));
		w10.X = 45;
		w10.Y = 160;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("2\'ere");
		this.fixed2.Add(this.label3);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label3]));
		w11.X = 45;
		w11.Y = 190;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("3\'ere");
		this.fixed2.Add(this.label4);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label4]));
		w12.X = 45;
		w12.Y = 220;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("4\'ere");
		this.fixed2.Add(this.label5);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label5]));
		w13.X = 45;
		w13.Y = 250;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("5\'ere");
		this.fixed2.Add(this.label6);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label6]));
		w14.X = 45;
		w14.Y = 280;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("6\'ere");
		this.fixed2.Add(this.label7);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label7]));
		w15.X = 45;
		w15.Y = 310;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.Xalign = 0F;
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("SUM");
		this.fixed2.Add(this.label8);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label8]));
		w16.X = 45;
		w16.Y = 340;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Bonus");
		this.fixed2.Add(this.label9);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label9]));
		w17.X = 45;
		w17.Y = 370;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("1 par");
		this.fixed2.Add(this.label10);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label10]));
		w18.X = 45;
		w18.Y = 400;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("2 par");
		this.fixed2.Add(this.label11);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label11]));
		w19.X = 45;
		w19.Y = 430;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("4 ens");
		this.fixed2.Add(this.label13);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label13]));
		w20.X = 45;
		w20.Y = 490;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("3 ens");
		this.fixed2.Add(this.label12);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label12]));
		w21.X = 45;
		w21.Y = 460;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Lille");
		this.fixed2.Add(this.label14);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label14]));
		w22.X = 45;
		w22.Y = 520;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.label15.Xalign = 0F;
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Stor");
		this.fixed2.Add(this.label15);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label15]));
		w23.X = 45;
		w23.Y = 550;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label16 = new global::Gtk.Label();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Hus");
		this.fixed2.Add(this.label16);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label16]));
		w24.X = 45;
		w24.Y = 580;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Chancen");
		this.fixed2.Add(this.label17);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label17]));
		w25.X = 45;
		w25.Y = 610;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label18 = new global::Gtk.Label();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Yatzy");
		this.fixed2.Add(this.label18);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label18]));
		w26.X = 45;
		w26.Y = 640;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label19 = new global::Gtk.Label();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("SUM");
		this.fixed2.Add(this.label19);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label19]));
		w27.X = 45;
		w27.Y = 670;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label20 = new global::Gtk.Label();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Spiller 1");
		this.fixed2.Add(this.label20);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label20]));
		w28.X = 145;
		w28.Y = 110;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label21 = new global::Gtk.Label();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Spiller 2");
		this.fixed2.Add(this.label21);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label21]));
		w29.X = 245;
		w29.Y = 110;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label22 = new global::Gtk.Label();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Spiller 3");
		this.fixed2.Add(this.label22);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label22]));
		w30.X = 345;
		w30.Y = 110;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.NavnSpiller1 = new global::Gtk.Entry();
		this.NavnSpiller1.WidthRequest = 100;
		this.NavnSpiller1.CanFocus = true;
		this.NavnSpiller1.Name = "NavnSpiller1";
		this.NavnSpiller1.IsEditable = false;
		this.NavnSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.NavnSpiller1);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.NavnSpiller1]));
		w31.X = 140;
		w31.Y = 125;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.enereSpiller1 = new global::Gtk.Entry();
		this.enereSpiller1.WidthRequest = 100;
		this.enereSpiller1.CanFocus = true;
		this.enereSpiller1.Name = "enereSpiller1";
		this.enereSpiller1.IsEditable = false;
		this.enereSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.enereSpiller1);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.enereSpiller1]));
		w32.X = 140;
		w32.Y = 155;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.toereSpiller1 = new global::Gtk.Entry();
		this.toereSpiller1.WidthRequest = 100;
		this.toereSpiller1.CanFocus = true;
		this.toereSpiller1.Name = "toereSpiller1";
		this.toereSpiller1.IsEditable = false;
		this.toereSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.toereSpiller1);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.toereSpiller1]));
		w33.X = 140;
		w33.Y = 185;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.treereSpiller1 = new global::Gtk.Entry();
		this.treereSpiller1.WidthRequest = 100;
		this.treereSpiller1.CanFocus = true;
		this.treereSpiller1.Name = "treereSpiller1";
		this.treereSpiller1.IsEditable = false;
		this.treereSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.treereSpiller1);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.treereSpiller1]));
		w34.X = 140;
		w34.Y = 215;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.fireereSpiller1 = new global::Gtk.Entry();
		this.fireereSpiller1.WidthRequest = 100;
		this.fireereSpiller1.CanFocus = true;
		this.fireereSpiller1.Name = "fireereSpiller1";
		this.fireereSpiller1.IsEditable = false;
		this.fireereSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.fireereSpiller1);
		global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.fireereSpiller1]));
		w35.X = 140;
		w35.Y = 245;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.femereSpiller1 = new global::Gtk.Entry();
		this.femereSpiller1.WidthRequest = 100;
		this.femereSpiller1.CanFocus = true;
		this.femereSpiller1.Name = "femereSpiller1";
		this.femereSpiller1.IsEditable = false;
		this.femereSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.femereSpiller1);
		global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.femereSpiller1]));
		w36.X = 140;
		w36.Y = 275;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.seksereSpiller1 = new global::Gtk.Entry();
		this.seksereSpiller1.WidthRequest = 100;
		this.seksereSpiller1.CanFocus = true;
		this.seksereSpiller1.Name = "seksereSpiller1";
		this.seksereSpiller1.IsEditable = false;
		this.seksereSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.seksereSpiller1);
		global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.seksereSpiller1]));
		w37.X = 140;
		w37.Y = 305;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.DelSumSpiller1 = new global::Gtk.Entry();
		this.DelSumSpiller1.WidthRequest = 100;
		this.DelSumSpiller1.CanFocus = true;
		this.DelSumSpiller1.Name = "DelSumSpiller1";
		this.DelSumSpiller1.IsEditable = false;
		this.DelSumSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.DelSumSpiller1);
		global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.DelSumSpiller1]));
		w38.X = 140;
		w38.Y = 335;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.BonusSpiller1 = new global::Gtk.Entry();
		this.BonusSpiller1.WidthRequest = 100;
		this.BonusSpiller1.CanFocus = true;
		this.BonusSpiller1.Name = "BonusSpiller1";
		this.BonusSpiller1.IsEditable = false;
		this.BonusSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.BonusSpiller1);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.BonusSpiller1]));
		w39.X = 140;
		w39.Y = 365;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.etparSpiller1 = new global::Gtk.Entry();
		this.etparSpiller1.WidthRequest = 100;
		this.etparSpiller1.CanFocus = true;
		this.etparSpiller1.Name = "etparSpiller1";
		this.etparSpiller1.IsEditable = false;
		this.etparSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.etparSpiller1);
		global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.etparSpiller1]));
		w40.X = 140;
		w40.Y = 395;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.toparSpiller1 = new global::Gtk.Entry();
		this.toparSpiller1.WidthRequest = 100;
		this.toparSpiller1.CanFocus = true;
		this.toparSpiller1.Name = "toparSpiller1";
		this.toparSpiller1.IsEditable = false;
		this.toparSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.toparSpiller1);
		global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.toparSpiller1]));
		w41.X = 140;
		w41.Y = 425;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.treensSpiller1 = new global::Gtk.Entry();
		this.treensSpiller1.WidthRequest = 100;
		this.treensSpiller1.CanFocus = true;
		this.treensSpiller1.Name = "treensSpiller1";
		this.treensSpiller1.IsEditable = false;
		this.treensSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.treensSpiller1);
		global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.treensSpiller1]));
		w42.X = 140;
		w42.Y = 455;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.fireensSpiller1 = new global::Gtk.Entry();
		this.fireensSpiller1.WidthRequest = 100;
		this.fireensSpiller1.CanFocus = true;
		this.fireensSpiller1.Name = "fireensSpiller1";
		this.fireensSpiller1.IsEditable = false;
		this.fireensSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.fireensSpiller1);
		global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.fireensSpiller1]));
		w43.X = 140;
		w43.Y = 485;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.LilleSpiller1 = new global::Gtk.Entry();
		this.LilleSpiller1.WidthRequest = 100;
		this.LilleSpiller1.CanFocus = true;
		this.LilleSpiller1.Name = "LilleSpiller1";
		this.LilleSpiller1.IsEditable = false;
		this.LilleSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.LilleSpiller1);
		global::Gtk.Fixed.FixedChild w44 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.LilleSpiller1]));
		w44.X = 140;
		w44.Y = 515;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.StorSpiller1 = new global::Gtk.Entry();
		this.StorSpiller1.WidthRequest = 100;
		this.StorSpiller1.CanFocus = true;
		this.StorSpiller1.Name = "StorSpiller1";
		this.StorSpiller1.IsEditable = false;
		this.StorSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.StorSpiller1);
		global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.StorSpiller1]));
		w45.X = 140;
		w45.Y = 545;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.HusSpiller1 = new global::Gtk.Entry();
		this.HusSpiller1.WidthRequest = 100;
		this.HusSpiller1.CanFocus = true;
		this.HusSpiller1.Name = "HusSpiller1";
		this.HusSpiller1.IsEditable = false;
		this.HusSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.HusSpiller1);
		global::Gtk.Fixed.FixedChild w46 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.HusSpiller1]));
		w46.X = 140;
		w46.Y = 575;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.ChancenSpiller1 = new global::Gtk.Entry();
		this.ChancenSpiller1.WidthRequest = 100;
		this.ChancenSpiller1.CanFocus = true;
		this.ChancenSpiller1.Name = "ChancenSpiller1";
		this.ChancenSpiller1.IsEditable = false;
		this.ChancenSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.ChancenSpiller1);
		global::Gtk.Fixed.FixedChild w47 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.ChancenSpiller1]));
		w47.X = 140;
		w47.Y = 605;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.YatzySpiller1 = new global::Gtk.Entry();
		this.YatzySpiller1.WidthRequest = 100;
		this.YatzySpiller1.CanFocus = true;
		this.YatzySpiller1.Name = "YatzySpiller1";
		this.YatzySpiller1.IsEditable = false;
		this.YatzySpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.YatzySpiller1);
		global::Gtk.Fixed.FixedChild w48 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.YatzySpiller1]));
		w48.X = 140;
		w48.Y = 635;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.SumSpiller1 = new global::Gtk.Entry();
		this.SumSpiller1.WidthRequest = 100;
		this.SumSpiller1.CanFocus = true;
		this.SumSpiller1.Name = "SumSpiller1";
		this.SumSpiller1.IsEditable = false;
		this.SumSpiller1.InvisibleChar = '●';
		this.fixed2.Add(this.SumSpiller1);
		global::Gtk.Fixed.FixedChild w49 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.SumSpiller1]));
		w49.X = 140;
		w49.Y = 665;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.NavnSpiller2 = new global::Gtk.Entry();
		this.NavnSpiller2.WidthRequest = 100;
		this.NavnSpiller2.CanFocus = true;
		this.NavnSpiller2.Name = "NavnSpiller2";
		this.NavnSpiller2.IsEditable = false;
		this.NavnSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.NavnSpiller2);
		global::Gtk.Fixed.FixedChild w50 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.NavnSpiller2]));
		w50.X = 240;
		w50.Y = 125;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.enereSpiller2 = new global::Gtk.Entry();
		this.enereSpiller2.WidthRequest = 100;
		this.enereSpiller2.CanFocus = true;
		this.enereSpiller2.Name = "enereSpiller2";
		this.enereSpiller2.IsEditable = false;
		this.enereSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.enereSpiller2);
		global::Gtk.Fixed.FixedChild w51 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.enereSpiller2]));
		w51.X = 240;
		w51.Y = 155;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.toereSpiller2 = new global::Gtk.Entry();
		this.toereSpiller2.WidthRequest = 100;
		this.toereSpiller2.CanFocus = true;
		this.toereSpiller2.Name = "toereSpiller2";
		this.toereSpiller2.IsEditable = false;
		this.toereSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.toereSpiller2);
		global::Gtk.Fixed.FixedChild w52 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.toereSpiller2]));
		w52.X = 240;
		w52.Y = 185;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.treereSpiller2 = new global::Gtk.Entry();
		this.treereSpiller2.WidthRequest = 100;
		this.treereSpiller2.CanFocus = true;
		this.treereSpiller2.Name = "treereSpiller2";
		this.treereSpiller2.IsEditable = false;
		this.treereSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.treereSpiller2);
		global::Gtk.Fixed.FixedChild w53 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.treereSpiller2]));
		w53.X = 240;
		w53.Y = 215;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.fireereSpiller2 = new global::Gtk.Entry();
		this.fireereSpiller2.WidthRequest = 100;
		this.fireereSpiller2.CanFocus = true;
		this.fireereSpiller2.Name = "fireereSpiller2";
		this.fireereSpiller2.IsEditable = false;
		this.fireereSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.fireereSpiller2);
		global::Gtk.Fixed.FixedChild w54 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.fireereSpiller2]));
		w54.X = 240;
		w54.Y = 245;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.femereSpiller2 = new global::Gtk.Entry();
		this.femereSpiller2.WidthRequest = 100;
		this.femereSpiller2.CanFocus = true;
		this.femereSpiller2.Name = "femereSpiller2";
		this.femereSpiller2.IsEditable = false;
		this.femereSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.femereSpiller2);
		global::Gtk.Fixed.FixedChild w55 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.femereSpiller2]));
		w55.X = 240;
		w55.Y = 275;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.seksereSpiller2 = new global::Gtk.Entry();
		this.seksereSpiller2.WidthRequest = 100;
		this.seksereSpiller2.CanFocus = true;
		this.seksereSpiller2.Name = "seksereSpiller2";
		this.seksereSpiller2.IsEditable = false;
		this.seksereSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.seksereSpiller2);
		global::Gtk.Fixed.FixedChild w56 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.seksereSpiller2]));
		w56.X = 240;
		w56.Y = 305;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.DelSumSpiller2 = new global::Gtk.Entry();
		this.DelSumSpiller2.WidthRequest = 100;
		this.DelSumSpiller2.CanFocus = true;
		this.DelSumSpiller2.Name = "DelSumSpiller2";
		this.DelSumSpiller2.IsEditable = false;
		this.DelSumSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.DelSumSpiller2);
		global::Gtk.Fixed.FixedChild w57 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.DelSumSpiller2]));
		w57.X = 240;
		w57.Y = 335;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.BonusSpiller2 = new global::Gtk.Entry();
		this.BonusSpiller2.WidthRequest = 100;
		this.BonusSpiller2.CanFocus = true;
		this.BonusSpiller2.Name = "BonusSpiller2";
		this.BonusSpiller2.IsEditable = false;
		this.BonusSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.BonusSpiller2);
		global::Gtk.Fixed.FixedChild w58 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.BonusSpiller2]));
		w58.X = 240;
		w58.Y = 365;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.etparSpiller2 = new global::Gtk.Entry();
		this.etparSpiller2.WidthRequest = 100;
		this.etparSpiller2.CanFocus = true;
		this.etparSpiller2.Name = "etparSpiller2";
		this.etparSpiller2.IsEditable = false;
		this.etparSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.etparSpiller2);
		global::Gtk.Fixed.FixedChild w59 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.etparSpiller2]));
		w59.X = 240;
		w59.Y = 395;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.toparSpiller2 = new global::Gtk.Entry();
		this.toparSpiller2.WidthRequest = 100;
		this.toparSpiller2.CanFocus = true;
		this.toparSpiller2.Name = "toparSpiller2";
		this.toparSpiller2.IsEditable = false;
		this.toparSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.toparSpiller2);
		global::Gtk.Fixed.FixedChild w60 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.toparSpiller2]));
		w60.X = 240;
		w60.Y = 425;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.treensSpiller2 = new global::Gtk.Entry();
		this.treensSpiller2.WidthRequest = 100;
		this.treensSpiller2.CanFocus = true;
		this.treensSpiller2.Name = "treensSpiller2";
		this.treensSpiller2.IsEditable = false;
		this.treensSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.treensSpiller2);
		global::Gtk.Fixed.FixedChild w61 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.treensSpiller2]));
		w61.X = 240;
		w61.Y = 455;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.fireensSpiller2 = new global::Gtk.Entry();
		this.fireensSpiller2.WidthRequest = 100;
		this.fireensSpiller2.CanFocus = true;
		this.fireensSpiller2.Name = "fireensSpiller2";
		this.fireensSpiller2.IsEditable = false;
		this.fireensSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.fireensSpiller2);
		global::Gtk.Fixed.FixedChild w62 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.fireensSpiller2]));
		w62.X = 240;
		w62.Y = 485;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.LilleSpiller2 = new global::Gtk.Entry();
		this.LilleSpiller2.WidthRequest = 100;
		this.LilleSpiller2.CanFocus = true;
		this.LilleSpiller2.Name = "LilleSpiller2";
		this.LilleSpiller2.IsEditable = false;
		this.LilleSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.LilleSpiller2);
		global::Gtk.Fixed.FixedChild w63 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.LilleSpiller2]));
		w63.X = 240;
		w63.Y = 515;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.StorSpiller2 = new global::Gtk.Entry();
		this.StorSpiller2.WidthRequest = 100;
		this.StorSpiller2.CanFocus = true;
		this.StorSpiller2.Name = "StorSpiller2";
		this.StorSpiller2.IsEditable = false;
		this.StorSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.StorSpiller2);
		global::Gtk.Fixed.FixedChild w64 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.StorSpiller2]));
		w64.X = 240;
		w64.Y = 545;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.HusSpiller2 = new global::Gtk.Entry();
		this.HusSpiller2.WidthRequest = 100;
		this.HusSpiller2.CanFocus = true;
		this.HusSpiller2.Name = "HusSpiller2";
		this.HusSpiller2.IsEditable = false;
		this.HusSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.HusSpiller2);
		global::Gtk.Fixed.FixedChild w65 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.HusSpiller2]));
		w65.X = 240;
		w65.Y = 575;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.ChancenSpiller2 = new global::Gtk.Entry();
		this.ChancenSpiller2.WidthRequest = 100;
		this.ChancenSpiller2.CanFocus = true;
		this.ChancenSpiller2.Name = "ChancenSpiller2";
		this.ChancenSpiller2.IsEditable = false;
		this.ChancenSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.ChancenSpiller2);
		global::Gtk.Fixed.FixedChild w66 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.ChancenSpiller2]));
		w66.X = 240;
		w66.Y = 605;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.YatzySpiller2 = new global::Gtk.Entry();
		this.YatzySpiller2.WidthRequest = 100;
		this.YatzySpiller2.CanFocus = true;
		this.YatzySpiller2.Name = "YatzySpiller2";
		this.YatzySpiller2.IsEditable = false;
		this.YatzySpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.YatzySpiller2);
		global::Gtk.Fixed.FixedChild w67 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.YatzySpiller2]));
		w67.X = 240;
		w67.Y = 635;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.SumSpiller2 = new global::Gtk.Entry();
		this.SumSpiller2.WidthRequest = 100;
		this.SumSpiller2.CanFocus = true;
		this.SumSpiller2.Name = "SumSpiller2";
		this.SumSpiller2.IsEditable = false;
		this.SumSpiller2.InvisibleChar = '●';
		this.fixed2.Add(this.SumSpiller2);
		global::Gtk.Fixed.FixedChild w68 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.SumSpiller2]));
		w68.X = 240;
		w68.Y = 665;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.NavnSpiller3 = new global::Gtk.Entry();
		this.NavnSpiller3.WidthRequest = 100;
		this.NavnSpiller3.CanFocus = true;
		this.NavnSpiller3.Name = "NavnSpiller3";
		this.NavnSpiller3.IsEditable = false;
		this.NavnSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.NavnSpiller3);
		global::Gtk.Fixed.FixedChild w69 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.NavnSpiller3]));
		w69.X = 340;
		w69.Y = 125;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.enereSpiller3 = new global::Gtk.Entry();
		this.enereSpiller3.WidthRequest = 100;
		this.enereSpiller3.CanFocus = true;
		this.enereSpiller3.Name = "enereSpiller3";
		this.enereSpiller3.IsEditable = false;
		this.enereSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.enereSpiller3);
		global::Gtk.Fixed.FixedChild w70 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.enereSpiller3]));
		w70.X = 340;
		w70.Y = 155;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.toereSpiller3 = new global::Gtk.Entry();
		this.toereSpiller3.WidthRequest = 100;
		this.toereSpiller3.CanFocus = true;
		this.toereSpiller3.Name = "toereSpiller3";
		this.toereSpiller3.IsEditable = false;
		this.toereSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.toereSpiller3);
		global::Gtk.Fixed.FixedChild w71 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.toereSpiller3]));
		w71.X = 340;
		w71.Y = 185;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.treereSpiller3 = new global::Gtk.Entry();
		this.treereSpiller3.WidthRequest = 100;
		this.treereSpiller3.CanFocus = true;
		this.treereSpiller3.Name = "treereSpiller3";
		this.treereSpiller3.IsEditable = false;
		this.treereSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.treereSpiller3);
		global::Gtk.Fixed.FixedChild w72 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.treereSpiller3]));
		w72.X = 340;
		w72.Y = 215;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.fireereSpiller3 = new global::Gtk.Entry();
		this.fireereSpiller3.WidthRequest = 100;
		this.fireereSpiller3.CanFocus = true;
		this.fireereSpiller3.Name = "fireereSpiller3";
		this.fireereSpiller3.IsEditable = false;
		this.fireereSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.fireereSpiller3);
		global::Gtk.Fixed.FixedChild w73 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.fireereSpiller3]));
		w73.X = 340;
		w73.Y = 245;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.femereSpiller3 = new global::Gtk.Entry();
		this.femereSpiller3.WidthRequest = 100;
		this.femereSpiller3.CanFocus = true;
		this.femereSpiller3.Name = "femereSpiller3";
		this.femereSpiller3.IsEditable = false;
		this.femereSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.femereSpiller3);
		global::Gtk.Fixed.FixedChild w74 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.femereSpiller3]));
		w74.X = 340;
		w74.Y = 275;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.seksereSpiller3 = new global::Gtk.Entry();
		this.seksereSpiller3.WidthRequest = 100;
		this.seksereSpiller3.CanFocus = true;
		this.seksereSpiller3.Name = "seksereSpiller3";
		this.seksereSpiller3.IsEditable = false;
		this.seksereSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.seksereSpiller3);
		global::Gtk.Fixed.FixedChild w75 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.seksereSpiller3]));
		w75.X = 340;
		w75.Y = 305;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.DelSumSpiller3 = new global::Gtk.Entry();
		this.DelSumSpiller3.WidthRequest = 100;
		this.DelSumSpiller3.CanFocus = true;
		this.DelSumSpiller3.Name = "DelSumSpiller3";
		this.DelSumSpiller3.IsEditable = false;
		this.DelSumSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.DelSumSpiller3);
		global::Gtk.Fixed.FixedChild w76 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.DelSumSpiller3]));
		w76.X = 340;
		w76.Y = 335;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.BonusSpiller3 = new global::Gtk.Entry();
		this.BonusSpiller3.WidthRequest = 100;
		this.BonusSpiller3.CanFocus = true;
		this.BonusSpiller3.Name = "BonusSpiller3";
		this.BonusSpiller3.IsEditable = false;
		this.BonusSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.BonusSpiller3);
		global::Gtk.Fixed.FixedChild w77 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.BonusSpiller3]));
		w77.X = 340;
		w77.Y = 365;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.etparSpiller3 = new global::Gtk.Entry();
		this.etparSpiller3.WidthRequest = 100;
		this.etparSpiller3.CanFocus = true;
		this.etparSpiller3.Name = "etparSpiller3";
		this.etparSpiller3.IsEditable = false;
		this.etparSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.etparSpiller3);
		global::Gtk.Fixed.FixedChild w78 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.etparSpiller3]));
		w78.X = 340;
		w78.Y = 395;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.toparSpiller3 = new global::Gtk.Entry();
		this.toparSpiller3.WidthRequest = 100;
		this.toparSpiller3.CanFocus = true;
		this.toparSpiller3.Name = "toparSpiller3";
		this.toparSpiller3.IsEditable = false;
		this.toparSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.toparSpiller3);
		global::Gtk.Fixed.FixedChild w79 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.toparSpiller3]));
		w79.X = 340;
		w79.Y = 425;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.treensSpiller3 = new global::Gtk.Entry();
		this.treensSpiller3.WidthRequest = 100;
		this.treensSpiller3.CanFocus = true;
		this.treensSpiller3.Name = "treensSpiller3";
		this.treensSpiller3.IsEditable = false;
		this.treensSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.treensSpiller3);
		global::Gtk.Fixed.FixedChild w80 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.treensSpiller3]));
		w80.X = 340;
		w80.Y = 455;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.fireensSpiller3 = new global::Gtk.Entry();
		this.fireensSpiller3.WidthRequest = 100;
		this.fireensSpiller3.CanFocus = true;
		this.fireensSpiller3.Name = "fireensSpiller3";
		this.fireensSpiller3.IsEditable = false;
		this.fireensSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.fireensSpiller3);
		global::Gtk.Fixed.FixedChild w81 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.fireensSpiller3]));
		w81.X = 340;
		w81.Y = 485;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.LilleSpiller3 = new global::Gtk.Entry();
		this.LilleSpiller3.WidthRequest = 100;
		this.LilleSpiller3.CanFocus = true;
		this.LilleSpiller3.Name = "LilleSpiller3";
		this.LilleSpiller3.IsEditable = false;
		this.LilleSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.LilleSpiller3);
		global::Gtk.Fixed.FixedChild w82 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.LilleSpiller3]));
		w82.X = 340;
		w82.Y = 515;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.StorSpiller3 = new global::Gtk.Entry();
		this.StorSpiller3.WidthRequest = 100;
		this.StorSpiller3.CanFocus = true;
		this.StorSpiller3.Name = "StorSpiller3";
		this.StorSpiller3.IsEditable = false;
		this.StorSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.StorSpiller3);
		global::Gtk.Fixed.FixedChild w83 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.StorSpiller3]));
		w83.X = 340;
		w83.Y = 545;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.HusSpiller3 = new global::Gtk.Entry();
		this.HusSpiller3.WidthRequest = 100;
		this.HusSpiller3.CanFocus = true;
		this.HusSpiller3.Name = "HusSpiller3";
		this.HusSpiller3.IsEditable = false;
		this.HusSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.HusSpiller3);
		global::Gtk.Fixed.FixedChild w84 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.HusSpiller3]));
		w84.X = 340;
		w84.Y = 575;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.ChancenSpiller3 = new global::Gtk.Entry();
		this.ChancenSpiller3.WidthRequest = 100;
		this.ChancenSpiller3.CanFocus = true;
		this.ChancenSpiller3.Name = "ChancenSpiller3";
		this.ChancenSpiller3.IsEditable = false;
		this.ChancenSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.ChancenSpiller3);
		global::Gtk.Fixed.FixedChild w85 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.ChancenSpiller3]));
		w85.X = 340;
		w85.Y = 605;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.YatzySpiller3 = new global::Gtk.Entry();
		this.YatzySpiller3.WidthRequest = 100;
		this.YatzySpiller3.CanFocus = true;
		this.YatzySpiller3.Name = "YatzySpiller3";
		this.YatzySpiller3.IsEditable = false;
		this.YatzySpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.YatzySpiller3);
		global::Gtk.Fixed.FixedChild w86 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.YatzySpiller3]));
		w86.X = 340;
		w86.Y = 635;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.SumSpiller3 = new global::Gtk.Entry();
		this.SumSpiller3.WidthRequest = 100;
		this.SumSpiller3.CanFocus = true;
		this.SumSpiller3.Name = "SumSpiller3";
		this.SumSpiller3.IsEditable = false;
		this.SumSpiller3.InvisibleChar = '●';
		this.fixed2.Add(this.SumSpiller3);
		global::Gtk.Fixed.FixedChild w87 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.SumSpiller3]));
		w87.X = 340;
		w87.Y = 665;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.HoldTerning1 = new global::Gtk.CheckButton();
		this.HoldTerning1.CanFocus = true;
		this.HoldTerning1.Name = "HoldTerning1";
		this.HoldTerning1.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.HoldTerning1.DrawIndicator = true;
		this.HoldTerning1.UseUnderline = true;
		this.fixed2.Add(this.HoldTerning1);
		global::Gtk.Fixed.FixedChild w88 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.HoldTerning1]));
		w88.X = 40;
		w88.Y = 70;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.HoldTerning2 = new global::Gtk.CheckButton();
		this.HoldTerning2.CanFocus = true;
		this.HoldTerning2.Name = "HoldTerning2";
		this.HoldTerning2.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.HoldTerning2.DrawIndicator = true;
		this.HoldTerning2.UseUnderline = true;
		this.fixed2.Add(this.HoldTerning2);
		global::Gtk.Fixed.FixedChild w89 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.HoldTerning2]));
		w89.X = 140;
		w89.Y = 70;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.HoldTerning3 = new global::Gtk.CheckButton();
		this.HoldTerning3.CanFocus = true;
		this.HoldTerning3.Name = "HoldTerning3";
		this.HoldTerning3.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.HoldTerning3.DrawIndicator = true;
		this.HoldTerning3.UseUnderline = true;
		this.fixed2.Add(this.HoldTerning3);
		global::Gtk.Fixed.FixedChild w90 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.HoldTerning3]));
		w90.X = 240;
		w90.Y = 70;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.HoldTerning4 = new global::Gtk.CheckButton();
		this.HoldTerning4.CanFocus = true;
		this.HoldTerning4.Name = "HoldTerning4";
		this.HoldTerning4.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.HoldTerning4.DrawIndicator = true;
		this.HoldTerning4.UseUnderline = true;
		this.fixed2.Add(this.HoldTerning4);
		global::Gtk.Fixed.FixedChild w91 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.HoldTerning4]));
		w91.X = 340;
		w91.Y = 70;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.HoldTerning5 = new global::Gtk.CheckButton();
		this.HoldTerning5.CanFocus = true;
		this.HoldTerning5.Name = "HoldTerning5";
		this.HoldTerning5.Label = global::Mono.Unix.Catalog.GetString("Hold");
		this.HoldTerning5.DrawIndicator = true;
		this.HoldTerning5.UseUnderline = true;
		this.fixed2.Add(this.HoldTerning5);
		global::Gtk.Fixed.FixedChild w92 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.HoldTerning5]));
		w92.X = 440;
		w92.Y = 70;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label23 = new global::Gtk.Label();
		this.label23.Name = "label23";
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Muligheder:");
		this.fixed2.Add(this.label23);
		global::Gtk.Fixed.FixedChild w93 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label23]));
		w93.X = 495;
		w93.Y = 110;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Vælg");
		this.fixed2.Add(this.button4);
		global::Gtk.Fixed.FixedChild w94 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.button4]));
		w94.X = 592;
		w94.Y = 98;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.mulighederCombo = global::Gtk.ComboBoxEntry.NewText();
		this.mulighederCombo.WidthRequest = 145;
		this.mulighederCombo.Name = "mulighederCombo";
		this.fixed2.Add(this.mulighederCombo);
		global::Gtk.Fixed.FixedChild w95 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.mulighederCombo]));
		w95.X = 490;
		w95.Y = 130;
		this.Add(this.fixed2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 780;
		this.DefaultHeight = 739;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.KastTerningKnap.Clicked += new global::System.EventHandler(this.OnKastTerningKnapClicked);
	}
}
